server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: MicroService-1
          uri: http://localhost:8085/
          predicates:
            - Path=/microservice1/**
        - id: MicroService-2
          uri: http://localhost:8082/
          predicates:
            - Path=/microservice2/**
